apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    eventing.knative.dev/connector: timer-source
  name: kn-connector-source-timer
spec:
  selector:
    matchLabels:
      eventing.knative.dev/connector: timer-source
  template:
    metadata:
      labels:
        eventing.knative.dev/connector: timer-source
    spec:
      containers:
      - name: kn-connector-source-timer
        env:
          - name: CAMEL_KAMELET_TIMER_SOURCE_MESSAGE
            value: "{{configmap:my-source-config/message}}"
          - name: CAMEL_KAMELET_TIMER_SOURCE_PERIOD
            value: "{{configmap:my-source-config/period}}"
        volumeMounts:
          - mountPath: /etc/camel/conf.d/_configmaps/my-source-config
            name: source-config
            readOnly: true
      volumes:
        - configMap:
            name: my-source-config
          name: source-config
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  annotations:
    sources.knative.dev/creator: connectors.knative.dev
  finalizers:
    - sinkbindings.sources.knative.dev
  labels:
    eventing.knative.dev/connector: timer-source
  name: kn-connector-source-timer
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
  subject:
    apiVersion: apps/v1
    kind: Deployment
    name: kn-connector-source-timer
